spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: root
    password: postgres

  jpa:
    properties:
      hibernate.format_sql: true

logging:
  level:
    cn.edu.seu.bookstore.mapper: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

project:
  security:
    expiration: 3600000
    expiration_remember: 604800000
    jwt_secret_key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    token_prefix: "Bearer "
