spring:
  profiles:
    active: @env@
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.edu.seu.bookstore
