spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username:
    password:

  jpa:
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql: TRACE