spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username:
    password:

  jpa:
    properties:
      hibernate.format_sql: true

logging:
  level:
    cn.edu.seu.bookstore.mapper: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG

project:
  security:
    expiration: 3600
    expiration_remember: 604800
    jwt_secret_key:
    token_prefix: "Bearer "
